

pretrained_model_path: "/mnt/workspace/cailingling/models/zeroscope_v2_576w"
dataset_config:
    path: "dataset/frames/bear"
    prompt: "a bear is walking"
    n_sample_frame: 8
    sampling_rate: 1
    stride: 80
    offset: 
        left: 0
        right: 0
        top: 0
        bottom: 0

editing_config:
    cal_maps: True
    dataname: "bear"
    word: ["bear","bear"]
    use_invertion_latents: True
    use_inversion_attention: True
    guidance_scale: 7.5
    editing_prompts: [
        a bear is walking
    ]



    clip_length: "${..dataset_config.n_sample_frame}"
    sample_seeds: [0]
    

    num_inference_steps: 10
    prompt2prompt_edit: True

    
model_config:
    lora: 160
    SparseCausalAttention_index: ['mid'] 
    least_sc_channel: 640

test_pipeline_config:
    target: video_diffusion.pipelines.p2p_ddim_spatial_temporal.P2pDDIMSpatioTemporalPipeline
    num_inference_steps: "${..validation_sample_logger.num_inference_steps}"



seed: 0

